/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-02-11 03:03:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      csci4300.Student student = null;
      synchronized (session) {
        student = (csci4300.Student) _jspx_page_context.getAttribute("student", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (student == null){
          student = new csci4300.Student();
          _jspx_page_context.setAttribute("student", student, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("student"), "studentName", "Nathan Ray", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("student"), "description", "I am a Senior at the University of Georgia with aspirations in financial software development. I love the puzzle that coding provides and spend most of my time with my nose in a book.", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("student"), "imageURL", "", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("student"), "activityStatement", "", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("student"), "newActivity", request.getParameter("newActivity"), request, "newActivity", false);
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("#activityBox {border-style:solid; border-width:thick; border-color:red; font-family:Arial,Sans-serif}\r\n");
      out.write("p.textStyling {font-weight:bold; font-style:italic}\r\n");
      out.write("#boldTextAndCenter {font-weight:bold; text-align:center}\r\n");
      out.write("p.spacing {width:45%}\r\n");
      out.write("td.textCenter {text-align:center}\r\n");
      out.write("#boldText {font-weight:bold}\r\n");
      out.write("\r\n");
      out.write("table.center {margin-left:auto; margin-right:auto}\r\n");
      out.write("\r\n");
      out.write("body {background-image:url('bigWave.jpg'); background-size:100%}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Student Profile</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>Student Profile</h1>\r\n");
      out.write("\r\n");
      out.write("<div><img src=\"Nathan_Ray.JPG\" style=\"float:right\" width=\"300\" height=\"350\" alt=\"Student Photo\"></div>\r\n");
      out.write("\r\n");
      out.write("<p class=\"textStyling\">Student Name:</p> \r\n");
      out.write("<p class=\"spacing\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((csci4300.Student)_jspx_page_context.findAttribute("student")).getStudentName())));
      out.write("</p>\r\n");
      out.write("<p class=\"textStyling\">Student Description:</p> \r\n");
      out.write("<p class=\"spacing\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((csci4300.Student)_jspx_page_context.findAttribute("student")).getDescription())));
      out.write("</p>\r\n");
      out.write("<p class=\"textStyling\">Student Activities:</p> \r\n");
      out.write("<p class=\"spacing\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((csci4300.Student)_jspx_page_context.findAttribute("student")).getActivityStatement())));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<h3 id=\"boldTextAndCenter\">Enter a new student activity:</h3>\r\n");
      out.write("\r\n");
      out.write("<form name=\"activityForm\" method=\"get\" action=\"index.jsp\">\r\n");
      out.write("\r\n");
      out.write("<table class=\"center\" id=\"activityBox\" width=\"35%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("<tr><td class=\"textCenter\">Activity: <input type=\"text\" name=\"newActivity\"></td></tr>\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("<tr><td class=\"textCenter\"><input type=\"submit\" value=\"Submit Activity\"></td></tr>\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<p id=\"boldText\">Background Image: wallpapers.free-review.net</p>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
