package safetybus;

import java.awt.Dimension;

import javax.swing.GroupLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nathan
 */
public class GaugePanel extends JPanel 
{

    /**
	 * Creates the default serial version ID for this class
	 */
	private static final long serialVersionUID = 1L;
	
	
	/**
     * Creates new form GaugePanel
     */
    public GaugePanel() 
    {
    	
        initComponents();
        // TODO: Add the line of code below, this is the only change to this class
        this.setOpaque(false);
        
    }	// End of GaugePanel constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * The content of this method is always regenerated by the Form Editor.
     */
    private void initComponents() 
    {

        radial2Top1 = new eu.hansolo.steelseries.gauges.Radial2Top();
        displaySingle1 = new eu.hansolo.steelseries.gauges.DisplaySingle();

        radial2Top1.setLcdUnitString("rating");
        radial2Top1.setLcdUnitStringVisible(true);
        // Sets value of the LCD
        radial2Top1.setLcdValue(0.0);
        radial2Top1.setMaxValue(10.0);
        radial2Top1.setName("Full Tank");
        radial2Top1.setTitle("User Reviews");
        radial2Top1.setTitleAndUnitFontEnabled(true);
        radial2Top1.setUnitString("Full Tank");
        // Sets the value of the radial
        radial2Top1.setValue(0.0);

        displaySingle1.setLcdUnitString("Rating");
        displaySingle1.setLcdValue(0.0);
        
        GroupLayout displaySingle1Layout = new GroupLayout(displaySingle1);
        displaySingle1.setLayout(displaySingle1Layout);
        displaySingle1Layout.setHorizontalGroup(displaySingle1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 128, Short.MAX_VALUE));
        displaySingle1Layout.setVerticalGroup(displaySingle1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 48, Short.MAX_VALUE));

        GroupLayout radial2Top1Layout = new javax.swing.GroupLayout(radial2Top1);
        radial2Top1.setLayout(radial2Top1Layout);
        radial2Top1Layout.setHorizontalGroup(radial2Top1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, radial2Top1Layout.createSequentialGroup().addContainerGap(82, Short.MAX_VALUE).addComponent(displaySingle1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addGap(79, 79, 79)));
        radial2Top1Layout.setVerticalGroup(radial2Top1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, radial2Top1Layout.createSequentialGroup().addGap(0, 193, Short.MAX_VALUE).addComponent(displaySingle1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addGap(48, 48, 48)));

        GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(radial2Top1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(radial2Top1, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE).addGap(0, 0, 0)));
        
        radial2Top1.setPreferredSize(new Dimension(10, 10));
        
    }	// End of initComponents method
    
    public double getObjectValue()
    {
    	
    	return radial2Top1.getValue();
    	
    }
    
    public void setObjectValue(double value)
    {
    	
    	//radial2Top1.setLcdValue(value);
    	displaySingle1.setLcdValue(value);
    	radial2Top1.setValue(value);
    	
    	if(radial2Top1.getValue() <= 3.0)
        {
        	
        	radial2Top1.setLedBlinking(true);
        	
        }	// End of if statement
    	
    }
    
    		// Variables declaration
    protected eu.hansolo.steelseries.gauges.DisplaySingle displaySingle1;
    protected eu.hansolo.steelseries.gauges.Radial2Top radial2Top1;
    		// End of variables declaration
    
}	// End of class GaugePanel
