/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-02-05 19:00:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      creditcard.CustomerAccount account = null;
      synchronized (session) {
        account = (creditcard.CustomerAccount) _jspx_page_context.getAttribute("account", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (account == null){
          account = new creditcard.CustomerAccount();
          _jspx_page_context.setAttribute("account", account, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "accountNo", "1", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "custName", "Gordon Gecko", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "custAddress", "1 Wall Street, NYC", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "creditLimit", "10000000.00", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "imageUrl", "http://cedricmnich.files.wordpress.com/2007/11/gordongecko.gif", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "errorMessage", "", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "unpaidBalanceFormatted", "", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "creditLimitFormatted", "", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("account"), "purchaseAmount", request.getParameter("purchaseAmount"), request, "purchaseAmount", false);
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("#inputBox {border-style:solid; border-width:thick; border-color:green; font-family:Arial,Sans-serif}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Customer Account</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>E-Z Credit, Inc.</h1>\r\n");
      out.write("\r\n");
      out.write("<div><img src=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((creditcard.CustomerAccount)_jspx_page_context.findAttribute("account")).getImageUrl())));
      out.write("\" style=\"float:right\" width=\"226\" height=\"284\"></div>\r\n");
      out.write("\r\n");
      out.write("<p>Valued Customer: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((creditcard.CustomerAccount)_jspx_page_context.findAttribute("account")).getCustName())));
      out.write("</p>\r\n");
      out.write("<p>Address: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((creditcard.CustomerAccount)_jspx_page_context.findAttribute("account")).getCustAddress())));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>Unpaid Balance: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((creditcard.CustomerAccount)_jspx_page_context.findAttribute("account")).getUnpaidBalanceFormatted())));
      out.write("</p>\r\n");
      out.write("<p>Credit Limit: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((creditcard.CustomerAccount)_jspx_page_context.findAttribute("account")).getCreditLimitFormatted())));
      out.write("</p>\r\n");
      out.write("<p>Gordon Gecko image: cedricmich.wordpress.com</p>\r\n");
      out.write("\r\n");
      out.write("<h3>Enter a new purchase</h3>\r\n");
      out.write("\r\n");
      out.write("<form name=\"purchaseForm\" method=\"get\" action=\"index.jsp\">\r\n");
      out.write("\r\n");
      out.write("<table id=\"inputBox\" width=\"55%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("<tr><td>Purchase amount $<input type=\"text\" name=\"purchaseAmount\"></td></tr>\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("<tr><td><input type=\"submit\" value=\"Enter Purchase\"></td></tr>\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("<tr><td style=\"color:red; font-weight:bold\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((creditcard.CustomerAccount)_jspx_page_context.findAttribute("account")).getErrorMessage())));
      out.write("</td></tr>\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
