package com.example.tests;

import com.thoughtworks.selenium.*;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.regex.Pattern;

public class shoetitles {
	private Selenium selenium;

	@Before
	public void setUp() throws Exception {
		selenium = new DefaultSelenium("localhost", 4444, "*chrome", "http://manheim-shoe-store-test.herokuapp.com/");
		selenium.start();
	}

	@Test
	public void testShoetitles() throws Exception {
		selenium.open("/");
		selenium.select("id=brand", "label=Acorn");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Acorn's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Aetrex");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Aetrex's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Alexander McQueen");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Alexander McQueen's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Alexandre Birman");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Alexandre Birman's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Alberto Fermani");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Alberto Fermani's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Alice + Olivia");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Alice + Olivia's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Amalfi by Rangoni");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Amalfi by Rangoni's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Andre Assous");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Andre Assous's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Anyi Lu");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Anyi Lu's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=ALDO");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("ALDO's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Aquatalia by Marvin K");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Aquatalia by Marvin K's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Arche");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Arche's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Ariat");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Ariat's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Ash");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Ash's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=ASICS®");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("ASICS®'s Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Athena Alexander");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Athena Alexander's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Attilio Giusti Leombruni");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Attilio Giusti Leombruni's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=B Brian Atwood");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("B Brian Atwood's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Badgley Mischka");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Badgley Mischka's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=BC Footwear");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("BC Footwear's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=BCBGeneration");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("BCBGeneration's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=BCBGMAXAZRIA");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("BCBGMAXAZRIA's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Bed Stu");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Bed Stu's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
		selenium.click("link=Home");
		selenium.waitForPageToLoad("30000");
		selenium.select("id=brand", "label=Bernardo");
		selenium.click("id=search_button");
		selenium.waitForPageToLoad("30000");
		assertEquals("Bernardo's Shoes", selenium.getText("css=h2"));
		assertTrue(selenium.isElementPresent("css=h2"));
	}

	@After
	public void tearDown() throws Exception {
		selenium.stop();
	}
}
